// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQLtsIBBm0KY3IzeR1QEUsjrs6q7HFaz0',
    appId: '1:943808156274:web:86364757ea0769b59628eb',
    messagingSenderId: '943808156274',
    projectId: 'flutterfire-ui-codelab-e2657',
    authDomain: 'flutterfire-ui-codelab-e2657.firebaseapp.com',
    storageBucket: 'flutterfire-ui-codelab-e2657.appspot.com',
    measurementId: 'G-4E8Y6QZQE6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAFaoQBKnC9aWec8GrR9athpzqGPMCjkI',
    appId: '1:943808156274:android:2ea2e528a1a2376d9628eb',
    messagingSenderId: '943808156274',
    projectId: 'flutterfire-ui-codelab-e2657',
    storageBucket: 'flutterfire-ui-codelab-e2657.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiuA5LSyCcQTvGILtYq8WlRhE6oyyTrQE',
    appId: '1:943808156274:ios:a3478b025b8ec9ab9628eb',
    messagingSenderId: '943808156274',
    projectId: 'flutterfire-ui-codelab-e2657',
    storageBucket: 'flutterfire-ui-codelab-e2657.appspot.com',
    iosClientId: '943808156274-b5fjf5prmbr0n11dq02o5p6gdffarhgp.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiuA5LSyCcQTvGILtYq8WlRhE6oyyTrQE',
    appId: '1:943808156274:ios:a3478b025b8ec9ab9628eb',
    messagingSenderId: '943808156274',
    projectId: 'flutterfire-ui-codelab-e2657',
    storageBucket: 'flutterfire-ui-codelab-e2657.appspot.com',
    iosClientId: '943808156274-b5fjf5prmbr0n11dq02o5p6gdffarhgp.apps.googleusercontent.com',
    iosBundleId: 'com.example.complete',
  );
}
